apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meltano-csv-pvc
  namespace: meltano
spec:
  accessModes:
    - ReadWriteOnce # <-- Changed from ReadWriteMany to fix the Rancher local-path constraint
  resources:
    requests:
      storage: 1Gi
