apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: banvic-database-postgres-pvc    # Prefix updated with Release Name
  namespace: postgres                    # Target Namespace added
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: banvic-database-postgres-alpine-pod # Prefix updated with Release Name
  namespace: postgres                        # Target Namespace added
  labels:
    app: postgres
    release: banvic-database                 # Added tracking label for the release
spec:
  containers:
    - name: postgres
      image: postgres:16-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
          name: dbport
      env:
        - name: POSTGRES_PASSWORD
          value: "senhaSecreta123!" 
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
      volumeMounts:
        - name: postgres-data-volume
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data-volume
      persistentVolumeClaim:
        claimName: banvic-database-postgres-pvc # Updated to match the new PVC name
