apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  # Kubernetes automatically base64 encodes values provided in stringData
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "senhaSecreta123!"
  POSTGRES_DB: "postgres"
